folder-name: pycat
conf-url: https://raw.githubusercontent.com/AxoIsAxo/null.os/refs/heads/main/applications/pycat/pycat.conf
script-url: https://raw.githubusercontent.com/AxoIsAxo/null.os/refs/heads/main/applications/pycat/pycat.py
